import Vue from 'vue'
import {
	Button,
	Cell,
	CellGroup,
	NavBar,
	Toast,
	Swipe,
	SwipeItem,
	Popup,
	Card,
	Tabbar,
	TabbarItem,
	Tab,
	Tabs,
	Notify,
	Form,
	Field,
	DropdownMenu,
	DropdownItem,
	Empty,
	Calendar,
	CouponCell,
	CouponList,
	ContactCard,
	AddressEdit,
	SwitchCell,
	List,
	PullRefresh ,
} from 'vant'
Vue.use(List);
Vue.use(PullRefresh);
Vue.use(ContactCard);
Vue.use(SwitchCell);
Vue.use(AddressEdit);
Vue.use(Popup);
Vue.use(CouponCell);
Vue.use(CouponList);
Vue.use(Empty);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Calendar);
Vue.use(Button);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(NavBar);
Vue.use(Toast);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Card);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Notify);
Vue.use(Form);
Vue.use(Field);
